version: "3.9"
services:
  backend:
    build: ./DeepMerge
    container_name: deepmerge-backend
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/cmlre
      - REDIS_URL=redis://redis:6379/0
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
      - MINIO_BUCKET=cmlre-raw
    depends_on:
      - db
      - redis
      - minio
    ports:
      - "8000:8000"
    networks:
      - appnet

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: deepmerge-frontend
    environment:
      - VITE_API_BASE_URL=/
    depends_on:
      - backend
    ports:
      - "8080:80"
    networks:
      - appnet

  db:
    image: timescale/timescaledb:latest-pg16
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=cmlre
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - appnet

  redis:
    image: redis:7-alpine
    networks:
      - appnet

  minio:
    image: minio/minio:latest
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - appnet

volumes:
  db_data:
  minio_data:

networks:
  appnet:
    driver: bridge


